#!/usr/bin/env node
/**
 * Offline dry-run simulation.
 *
 *   node scripts/sync/simulate.mjs --file ./data/rsvps.xlsx
 *
 * Reconstructs the post-migration database from the spreadsheet's own export
 * columns — the sheet is a dump of `rsvps`, so every row carrying an `id`
 * already exists in the table — then runs the real planner and the real
 * report renderer against it.
 *
 * This is NOT a live run: it cannot see rows added since the export, and it
 * assumes the migration columns are still NULL. Use it to preview the shape
 * of the change set; run the genuine dry run for the authoritative answer.
 */

import { loadSource } from './sources/index.mjs';
import { planSync } from './engine.mjs';
import { printReport } from './report.mjs';
import { email as normEmail, phone as normPhone, text } from './normalize.mjs';

const fileArg = process.argv.indexOf('--file');
const file = fileArg > -1 ? process.argv[fileArg + 1] : './data/rsvps.xlsx';

const source = await loadSource({ file });

/** Mirrors compute_guest_count() from 0002 — main_invite_status is NULL pre-sync. */
const seats = (attending, plusStatus) => {
  if (attending === false) return 0;
  if (attending === true) {
    return ['APPROVED', 'ACCEPTED'].includes(String(plusStatus || '').toUpperCase()) ? 2 : 1;
  }
  return 0;
};

const pick = (v, k) => {
  if (k in v) return v[k];
  const hit = Object.keys(v).find(x => x.toLowerCase().trim() === k);
  return hit ? v[hit] : undefined;
};
const bool = v => (typeof v === 'boolean' ? v
  : ['true', 'yes', '1'].includes(String(v ?? '').trim().toLowerCase()) ? true
  : ['false', 'no', '0'].includes(String(v ?? '').trim().toLowerCase()) ? false : null);

// Rows bearing an id came out of the table, so they are what the table holds.
const existing = [];
for (const { values } of source.rows) {
  const id = text(pick(values, 'id'));
  if (!id) continue;

  const attending      = bool(pick(values, 'attending'));
  const plusOneStatus  = text(pick(values, 'plus_one_status'));
  const guest_count    = seats(attending, plusOneStatus);

  existing.push({
    id,
    full_name:             text(pick(values, 'full_name')),
    email:                 normEmail(pick(values, 'email')),
    phone:                 normPhone(pick(values, 'phone')),
    attending,
    guest_count,
    created_at:            text(pick(values, 'created_at')),
    plus_one_requested:    bool(pick(values, 'plus_one_requested')),
    plus_one_name:         text(pick(values, 'plus_one_name')),
    plus_one_relationship: text(pick(values, 'plus_one_relationship')),
    plus_one_status:       plusOneStatus ? plusOneStatus.toUpperCase() : null,

    // Added by 0001 — still NULL before the first sync.
    sheet_key: null, main_invite_status: null, approved_for: null,
    plus_one_approved_for: null, email_status: null, whatsapp_status: null,
    last_email_sent: null, last_whatsapp_sent: null, synced_at: null,

    // Generated by 0003.
    seat_allocation: guest_count === 0 ? 'None'
                   : guest_count === 1 ? 'Main Guest' : 'Main Guest + Plus One',
  });
}

console.log('\n\x1b[33m  SIMULATION — reconstructed from the export, not a live database read.\x1b[0m');
console.log(`\x1b[90m  Modelled ${existing.length} existing rows (sheet rows carrying an id).\x1b[0m`);

const plan = planSync(source, existing);
printReport({
  source: { ...source, name: `${source.name}  [simulated DB]` },
  plan,
  results: { inserted: 0, updated: 0, errors: [] },
  applied: false,
  existingCount: existing.length,
});
